---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - config-pvc.yaml # moved to iscsi
  - code-server-ssh-key.sops.yaml
  - home-assistant.sops.yaml
  - helm-release.yaml
