---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bazarr
  - bonob
  - channels-dvr
  - lidarr
  - navidrome
  - plex
  - radarr
  #- samba
  - sabnzbd
  - sonarr
  - tautulli
